
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: yhimu                # User for PostgreSQL
      POSTGRES_PASSWORD: 1234567           # Password for the user
      POSTGRES_DB: note-making             # Default database name
    ports:
      - "5432:5432"                        # Exposing PostgreSQL on port 5432
    volumes:
      - pg_data:/var/lib/postgresql/data    # Persisting data with Docker volumes

  backend:
    build:
      context: ./                  # Path to your backend directory
    environment:
      DB_USER: yhimu                       # Database user
      DB_PASSWORD: 1234567                 # Database password
      DB_NAME: note-making                  # Database name
      PORT: 5000                            # Port to run the backend
    ports:
      - "5000:5000"                        # Exposing backend service on port 5000
    depends_on:
      - postgres                            # Ensures PostgreSQL starts before backend
    volumes:
      - .:/usr/src/app             # Mounting backend code into the container

volumes:
  pg_data:                                # Defining a named volume for PostgreSQL data
